---
title: "lab1"
author: "Lillian Clark"
date: "8/30/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

$\beta_{(t+1)} = \beta^{(t)} -(-\sum_{i=1}^ne^{\textbf{X}_i\beta}\textbf{X}_i\textbf{X}_i^T)^{-1}(\sum_{i=1}^n(y_i - e^{\textbf{X}_i\beta})\textbf{X}_i^T)$

```{r}
bike <- read_csv("210830_bikecrash.csv")
# attempt to replicate these results

m1 <- glm(crashes ~ traffic_vol + pct_rural, 
          data = bike, 
          family = "poisson")
round(summary(m1)$coef[,1], 4)
```

```{r}
calc.score <- function(beta, X, y){
  d1 <- rep(0, length(beta))
  for(i in 1:length(y)){
    d1 <- d1 + (y[i] - exp(X[i,] %*% beta)) %*% X[i,]
  }
  return(colSums(d1))
}
```

```{r}
calc.hess <- function(beta, X, y){
  d1 <- rep(0, length(beta))
  for(i in 1:length(y)){
    d1 <- d1 + (exp(X[i,] %*% beta) %*% t(X[i,]) %*% X[i,])
  }
  return(-colSums(d1))
}
```


```{r}
crash <- bike$crashes
traf <- bike$traffic_vol

ex <- bind_cols(traf, bike$pct_rural) %>%
  janitor::clean_names()


# this does work
calc.score(as.matrix(c(1,1)), as.matrix(ex), as.matrix(crash))
# this does not
#calc.hess(as.matrix(c(1,1)), as.matrix(ex), as.matrix(crash))
```
